---
title: "Other APIs"
output:
  html_document:
    toc: true
    toc_float: true
---

Some notable other APIs useful for digital marketing are described below:

## Search Console

Get your SEO keywords back after `(not provided)` via Google's Search Console.

```r
## This installs searchConsoleR if you haven't got it already
if(!require(searchConsoleR)) install.packages("searchConsoleR")
library(searchConsoleR)

## authentication similar to googleAnalyticsR
scr_auth()

seo_data <- search_analytics("your-website.com", dimensions = c("date","query"))
```

## BigQuery

This is useful if you have Google Analytics data going into BigQuery from Google Analytics 360, as well as if you're using BigQuery with any other data. See [BigQuery section](http://code.markedmondson.me/googleAnalyticsR/big-query.html) of `googleAnalyticsR`.

```r
## This installs bigQueryR if you haven't got it already
if(!require(bigQueryR)) install.packages("bigQueryR")

library(googleAnalyticsR)

## Authentication similar to googleAnalyticsR
bqr_auth()

## This function turns GA dimensions/metrics into BigQuery SQL

bq <- google_analytics_bq("project-id", "dataset-id-ga-viewid", 
                           start = "2016-01-01", end = "2016-02-01", 
                           metrics = "users", 
                           dimensions = c("source","medium"))
head(bq)
             source   medium  users
1   mavas|blahbs.ru  display  47837
2          examp.ae referral   6090
3   lm.facebook.com referral    335
4       ghtie_yahoo  display 133900
5      fjsfs_inmobi  display  19887
6 tripadvisor.co.dk referral    307 

```

For more general BigQuery extracts, it may be better to use the more developed [bigrquery()](https://github.com/rstats-db/bigrquery) package instead.

## Twitter

Historically, the go-to package for getting Twitter data using R was [`twitteR`](https://github.com/geoffjentry/twitteR). But, the authors of that package have recently released a new package called [`rtweet`](https://github.com/mkearney/rtweet), which, along with being much easier to search Google for help with, offers quicker authentication options. 

## Facebook

[`Rfacebook`](https://github.com/pablobarbera/Rfacebook) offers Facebook user data, and [`fbRads`](https://github.com/cardcorp/fbRads) gets you connected to the Facebook Marketing API. 

## Make Your Own 

If you can't find an R library, then you can make your own.  [`httr`](https://github.com/hadley/httr) is what most of the packages are built on and comes with a [quickstart guide](https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html).