---
title: "Day 2 in R"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the data

```{r}
all_data <- readxl::read_excel("data/day2/SampleGA2 for R Mark.xlsx")
names(all_data)
```

The three files match to the following:

* Group 1 (row 2 - row 4055)
* Group 2 (row 4056 - 5906)
* Group 3 (row 5907 - 7163)

```{r}
## 1 indexed not including header row (1)
group_one <- all_data[1:4054, ]
group_two <- all_data[4055:5905, ]
group_three <- all_data[5906:7162, ]

all_groups <- list(group_one = group_one,
                   group_two = group_two,
                   group_three = group_three)
```

## Summary statistics

```{R}
library(psych) # statistics

my_summary <- function(x, metric){
  y <- x[, metric]
  ## do we need skewness/kutosis se too?      
  ## https://estatistics.eu/what-is-statistics-standard-error-of-skewness-standard-error-of-kurtosis/
  
  ## tidy summary
  describe(y)
}


lapply(all_groups, my_summary, metric = c("Sessions", "GoalCompletions"))

```

Create class statistics

```{r}
my_class_stats <- function(x, dimension){
  dim <- x[[dimension]]
  
  ## makes a dataframe of $Var1 and $Freq
  my_df <- as.data.frame(table(dim))
  sum_all <- sum(my_df$Freq)
  my_df$percent <- round(my_df$Freq / sum_all, 4)
  my_df$cum.percent <- cumsum(my_df$percent)
  
  my_df
}

## do we need to order factors?
lapply(all_groups, my_class_stats, dimension = "deviceCategory")
lapply(all_groups, my_class_stats, dimension = "channelGrouping")
```

## Cross Tabulation

```{r}

## how to calculate expected count here?
my_cross_table <- function(x, cross1, cross2){
  totals <- table(x[[cross1]], x[[cross2]])
  ## expected is weighted average 
  
  totals
}


lapply(all_groups, my_cross_table, cross1 = "deviceCategory", cross2 = "channelGrouping")

## how to calculate expected count here?
my_chi_table <- function(x, cross1, cross2){
  chisq.test(table(x[[cross1]], x[[cross2]]))
}

lapply(all_groups, my_chi_table, cross1 = "deviceCategory", cross2 = "channelGrouping")


## see if I can put in Cramers V and/or Phi to compare chi_Table comparisons

```


## ANOVA

```{r}

my_anova <- function(x, metric, dim){
  my_form <- as.formula(paste(metric, "~", dim))
  model <- aov(my_form , data = x)
  summary(model)
  
}

my_anova_tukey <- function(x, metric, dim){
  my_form <- as.formula(paste(metric, "~", dim))
  model <- aov(my_form , data = x)
  
  TukeyHSD(model)
}

my_nway_anova <- function(x, metric, dim){
  my_form <- as.formula(paste(metric, "~", dim))
  anova(lm(my_form , data = x))
}

lapply(all_groups, my_anova, metric = "Sessions", dim = "deviceCategory")
lapply(all_groups, my_anova, metric = "GoalCompletions", dim = "deviceCategory")


lapply(all_groups, my_anova, metric = "Sessions", dim = "channelGrouping")
lapply(all_groups, my_anova, metric = "GoalCompletions", dim = "channelGrouping")


## tests of between subject effects
lapply(all_groups, my_nway_anova, metric = "GoalCompletions", dim = "channelGrouping * deviceCategory")


```


## Regression outputs

```{r}
my_models_fun <- function(x, dependent, independent){
  my_form <- as.formula(paste(dependent, "~", independent))
  lm(my_form, data = x)
}

my_models <- lapply(all_groups, my_models_fun, dependent = "GoalCompletions", independent = "Sessions")
lapply(my_models, summary)

my_predict_mean <- function(x, model_string = "Sessions ~ GoalCompletions"){
  my_form <- as.formula(paste(model_string))
  model <- lm(my_form, data = x)
  cat("\nMean Sessions: ",mean(x$Sessions))
  cat("\nMean GoalCompletions",mean(x$GoalCompletions))
  predict(model, 
          newdata = data.frame(Sessions = mean(x$Sessions), GoalCompletions = mean(x$GoalCompletions)),
          interval = "predict",
          level = 0.95)
}

my_conf_interval <- function(x){
  model <- lm(Sessions ~ GoalCompletions + DeviceClass + ChannelClass, data = x)
  summary(model)
  confint(model, level = 0.95)
  
}

my_regression <- function(x){
  model <- lm(Sessions ~ GoalCompletions + DeviceClass + ChannelClass, data = x)
  summary(model)
}



## generate the upper and lower bound for beta coeffcients
lapply(all_groups, my_predict_mean)

lapply(all_groups, my_regression)
lapply(all_groups, my_conf_interval)
```